# Generated by Django 2.2.3 on 2019-07-27 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190724_2038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='isPublic',
            new_name='is_public',
        ),
    ]
