# Generated by Django 2.2.3 on 2019-07-25 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_public'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='public',
            new_name='isPublic',
        ),
    ]
